config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :show, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :email, :session_token, presence: true, uniqueness: true 
    validates :password_digest, presence: true
    validates :password, length: {minimum: 6}, allow_nil: true 

    attr_reader :password 
    before_validation :ensure_session_token 

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            return user
        else
            return nil 
        end
    end

    def password=(password)
        @password = password 
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = generate_unique_user_token
        self.save!
        return self.session_token
    end

    def ensure_session_token
        self.session_token ||= generate_unique_user_token
    end

    private 
    def generate_unique_user_token 
        token = SecureRandom::urlsafe_base64
        while User.exists?(session_token: token)
            token = SecureRandom::urlsafe_base64
        end
        return token 
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_user
    
    def current_user 
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in 
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out 
        redirect_to new_session_url unless logged_in?
    end

    def logged_in?
        !!current_user
        #note: not @current_user. I need to refer to the method called current_user
    end

    def login_user(user)
        session[:session_token] = user.reset_session_token!
        #note: if I call current_user here, then the @current_user only persists for the one cycle
    end

    def logout
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil 
        @current_user = nil 
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
        render :new 
    end

    def create #use the methods defined earlier in the users controller
        incoming_email = params[:user][:email]
        incoming_pw = params[:user][:password]
        @user = User.find_by_credentials(incoming_email, incoming_pw)
        if @user 
            login_user(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = ["no user"]
            render :new
        end
    end

    def destroy 
        logout
        redirect_to new_session_url 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find_by(id: params[:id])
        render :show 
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def new 
        @user = User.new
        render :new 
    end

    private 
    def user_params 
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>


  <body>
    
    <header> Music App </header>

    <div id="my_div">
      <% if logged_in? %>
        <h2>Welcome, <%= current_user.email %></h2>
        <form action="<%= session_url %>" method="POST">
          <input type="hidden" name="_method" value="DELETE">
          <!--Authenticity token stuff-->
            <input type="hidden" 
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
          <button>Log Out!</button>    
        </form>
      <% end %>
    </div>

  <main>
    <%= yield %>
  </main>

    <!--Flash for errors-->
    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <%= error %>
      <% end %>
    <% end %>
  </body>
</html>

app/views/users/create.html.erb
<h2>Create a user</h2>

app/views/users/index.html.erb
<h2>Welcome to the index page</h2>

<% @users = User.all %>
<% @users.each do |user| %>
  <li>Email: <%= user.email %></li>
<% end %>

<a href="<%=new_user_url%>">new_user</a> <br>
<a href="<%=new_session_url%>">login_user</a>

app/views/users/new.html.erb
<h2>New User</h2>

<form action="<%= users_url %>" method="POST">

    <!--Authenticity token stuff-->
    <input type="hidden" 
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

    <input type="text" name="user[email]" placeholder="email"><br>
    <input type="password" name="user[password]" placeholder="password"><br>
    <button>Submit</button>
    <br>
    <a href="<%= new_session_url %>">Go To Login Page</a>


</form>

app/views/users/show.html.erb
<h2>Current User</h2>
<p>Thanks for being our valued user</p>

<ul>
    <li><%= @user.email %></li>
</ul>

<a href="<%=new_user_url%>">Home Page</a>